### ISSUE TITLE
Los puntos optimos aproximados no coinciden con los puntos optimos reales en varios casos

### ISSUE THREAD

**Issue by AndresAlb** [MauricioTrejo/ProyectosAnalisisAplicado#2]
Al correr el script ScriptPruebaBusquedaBLHibrido este es el resultado:

`ROSENBROCK:

No hay suficiente descenso
Numero de iteraciones: 10
Derivada direccional: -0.0000000455

Punto optimo aproximado:

    0.9998    0.9995

Numero de iteraciones: 251

Punto optimo:

     1     1

RASTRIGIN:

Punto optimo aproximado:

    0.5025    0.9949

Numero de iteraciones: 87

Punto optimo:

     0     0

GRIEWANK:

Punto optimo aproximado:

    3.0696    0.0000

Numero de iteraciones: 250

Punto optimo:

     0     0

ACKLEY:

Punto optimo aproximado:

   -0.0000    1.6018

Numero de iteraciones: 250

Punto optimo:

     0     0

BRANIN:

No hay suficiente descenso
Numero de iteraciones:  3
Derivada direccional: -0.0000000000

Punto optimo aproximado:

   -3.1416   12.2750

Numero de iteraciones: 251

Puntos optimos:

   -3.1416   12.2750

    3.1416    2.2750

    9.4248    2.4750

EASOM:

No hay suficiente descenso
Numero de iteraciones:  1
Derivada direccional: -0.0000000093

Punto optimo aproximado:

    4.9782    4.9782

Numero de iteraciones: 251

Punto optimo:

    3.1416    3.1416`

**Comment by AndresAlb** [comment]
Esto fue lo que yo intenté para solucionarlo en el `while` que se encarga de hacer la busqueda de línea:

`
    %% Parte iterativa
    while ( ng > tol && iter < maxiter &&  norm(p)> 1e-04)

        %p = -g;                % Máximo descenso
        H = hessiana(fname, x);
        p = -H\g;               % Dirección de Newton
        
        alfa = 1;
        alfa_BT = 1;            % Paso completo
        alfa_IC = 1;            % Paso completo
        xt = x + p;             % Primer punto de prueba
        f  = feval(fname, x);   % Valor de la función
        f1 = feval(fname, xt);  % Valor de la función en el punto de prueba
        f2 = f1;                % Valor de la función en el punto de prueba
        s  = p'*g;              % Derivada direccional
        jter = 0;               % Iteraciones internas

        if( abs(s) < 1.e-06 )
            fprintf('\nNo hay suficiente descenso\n')
            fprintf('Numero de iteraciones: %2.0f', iter)
            fprintf('\nDerivada direccional: %2.10f\n', s)
            iter = maxiter; 
        end

        %% Búsqueda de línea
        while(f1 > f + alfa_BT*c1*s && f2 > f + alfa_IC*c1*s && jter < maxjter)

            % Backtracking
            alfa_BT = alfa_BT/2;

            % Interpolación cuadrática
            d2 = f2 - f - s;
            alfa_IC = -s/(2*d2);

            % Selección de alfa
            if(f1 <= f + alfa_BT*c1*s)
                if(f2 <= f + alfa_IC*c1*s)
                    % Backtracking e interpolación cuadrática cumplen Wolfe 1
                    alfa = max(alfa_BT, alfa_IC);
                end
            else
                % Sólo interpolación cuadrática cumple Wolfe 1
                if(f2 <= f + alfa_IC*c1*s)
                    alfa = alfa_IC;
                end
            end

            if(jter >= 20 || norm(alfa*p) < 1e-3)
                alfa = 1e-2;
            end
            
            % Actualización
            xt = x + alfa*p;
            f1 = feval(fname, xt);
            f2 = feval(fname, xt);
            jter = jter + 1;

        end
    
        % Actualización de valores
        x = x + alfa*p;
        g = gradiente(fname, x);
        iter = iter + 1;

    end`

**Comment by MauricioTrejo** [comment]
Ya creamos un branch para tener versiones con los puntos del proyecto y con los que sí convergen.
